name: C++ CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y g++
      
    - name: Build the application
      run: g++ main.cpp -o HelloWorld
      
    - name: Run the application
      run: ./HelloWorld

    - name: Run clang-tidy
      run: clang-tidy main.cpp -- -std=c++17  

    - name: Zip the executable
      run: zip setup.zip HelloWorld
      
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: setup-zip
        path: ./setup.zip
